
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 26 18:30:46 CET 2018
//----------------------------------------------------

import java.util.*;
import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Jan 26 18:30:46 CET 2018
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\003\000\002\002\004\000\002\003" +
    "\005\000\002\003\004\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\022\005\000\002\022\003\000\002\021" +
    "\003\000\002\021\005\000\002\006\004\000\002\006\004" +
    "\000\002\023\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\010\005\000\002\011\005\000\002\012\005\000\002\013" +
    "\005\000\002\014\013\000\002\015\005\000\002\016\003" +
    "\000\002\017\003\000\002\020\004\000\002\020\004\000" +
    "\002\020\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\012\004\016\012\022\014\004\015\020\001" +
    "\002\000\024\007\uffe1\010\uffe1\011\uffe1\017\uffe1\020\uffe1" +
    "\021\uffe1\022\uffe1\023\uffe1\024\uffe1\001\002\000\014\007" +
    "\uffea\010\uffea\011\uffea\023\uffea\024\uffea\001\002\000\006" +
    "\010\ufffc\011\ufffc\001\002\000\006\010\ufff9\011\ufff9\001" +
    "\002\000\014\007\uffeb\010\uffeb\011\uffeb\023\uffeb\024\uffeb" +
    "\001\002\000\006\010\ufffb\011\ufffb\001\002\000\014\007" +
    "\uffec\010\uffec\011\uffec\023\uffec\024\uffec\001\002\000\024" +
    "\007\uffe9\010\uffe9\011\uffe9\017\064\020\066\021\065\022" +
    "\067\023\uffe9\024\uffe9\001\002\000\004\002\063\001\002" +
    "\000\006\010\055\011\057\001\002\000\006\013\036\014" +
    "\004\001\002\000\014\007\uffed\010\uffed\011\uffed\023\uffed" +
    "\024\uffed\001\002\000\010\010\uffe2\011\uffe2\016\034\001" +
    "\002\000\006\010\ufffa\011\ufffa\001\002\000\012\013\030" +
    "\014\004\015\020\025\026\001\002\000\006\010\ufffd\011" +
    "\ufffd\001\002\000\004\002\001\001\002\000\006\010\ufff5" +
    "\011\ufff5\001\002\000\006\010\uffee\011\uffee\001\002\000" +
    "\006\010\ufff7\011\ufff7\001\002\000\006\010\ufff8\011\ufff8" +
    "\001\002\000\006\010\uffef\011\uffef\001\002\000\006\010" +
    "\ufff0\011\ufff0\001\002\000\006\010\ufff6\011\ufff6\001\002" +
    "\000\004\014\004\001\002\000\006\010\uffe3\011\uffe3\001" +
    "\002\000\006\007\ufff2\024\ufff2\001\002\000\006\007\ufff3" +
    "\024\053\001\002\000\004\023\051\001\002\000\004\007" +
    "\042\001\002\000\004\011\043\001\002\000\012\004\016" +
    "\012\022\014\004\015\020\001\002\000\004\006\045\001" +
    "\002\000\004\011\046\001\002\000\012\004\016\012\022" +
    "\014\004\015\020\001\002\000\004\005\050\001\002\000" +
    "\006\010\uffe4\011\uffe4\001\002\000\004\014\004\001\002" +
    "\000\006\007\ufff1\024\ufff1\001\002\000\006\013\036\014" +
    "\004\001\002\000\004\007\ufff4\001\002\000\024\002\uffde" +
    "\004\uffde\005\uffde\006\uffde\010\055\011\057\012\uffde\014" +
    "\uffde\015\uffde\001\002\000\020\002\ufffe\004\016\005\ufffe" +
    "\006\ufffe\012\022\014\004\015\020\001\002\000\024\002" +
    "\uffdd\004\uffdd\005\uffdd\006\uffdd\010\055\011\057\012\uffdd" +
    "\014\uffdd\015\uffdd\001\002\000\020\002\uffdf\004\uffdf\005" +
    "\uffdf\006\uffdf\012\uffdf\014\uffdf\015\uffdf\001\002\000\010" +
    "\002\uffff\005\uffff\006\uffff\001\002\000\020\002\uffe0\004" +
    "\uffe0\005\uffe0\006\uffe0\012\uffe0\014\uffe0\015\uffe0\001\002" +
    "\000\004\002\000\001\002\000\004\014\004\001\002\000" +
    "\004\014\004\001\002\000\004\014\004\001\002\000\004" +
    "\014\004\001\002\000\014\007\uffe5\010\uffe5\011\uffe5\023" +
    "\uffe5\024\uffe5\001\002\000\014\007\uffe7\010\uffe7\011\uffe7" +
    "\023\uffe7\024\uffe7\001\002\000\014\007\uffe6\010\uffe6\011" +
    "\uffe6\023\uffe6\024\uffe6\001\002\000\014\007\uffe8\010\uffe8" +
    "\011\uffe8\023\uffe8\024\uffe8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\034\002\013\003\023\004\014\006\022\007" +
    "\020\010\016\011\011\012\007\013\004\014\006\015\005" +
    "\016\010\017\012\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\020\055\001\001\000\022\007\037" +
    "\010\016\011\011\012\007\013\004\017\012\021\036\022" +
    "\040\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\005\031\007\032\010\016\011\011\012" +
    "\007\013\004\015\024\016\026\017\012\023\030\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\007" +
    "\034\010\016\011\011\012\007\013\004\017\012\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\032" +
    "\003\043\004\014\006\022\007\020\010\016\011\011\012" +
    "\007\013\004\014\006\015\005\016\010\017\012\001\001" +
    "\000\002\001\001\000\002\001\001\000\032\003\046\004" +
    "\014\006\022\007\020\010\016\011\011\012\007\013\004" +
    "\014\006\015\005\016\010\017\012\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\007\051\010\016\011\011" +
    "\012\007\013\004\017\012\001\001\000\002\001\001\000" +
    "\022\007\037\010\016\011\011\012\007\013\004\017\012" +
    "\021\036\022\053\001\001\000\002\001\001\000\004\020" +
    "\061\001\001\000\032\003\060\004\014\006\022\007\020" +
    "\010\016\011\011\012\007\013\004\014\006\015\005\016" +
    "\010\017\012\001\001\000\004\020\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\007\072\010\016\011\011\012\007\013\004" +
    "\017\012\001\001\000\016\007\071\010\016\011\011\012" +
    "\007\013\004\017\012\001\001\000\016\007\070\010\016" +
    "\011\011\012\007\013\004\017\012\001\001\000\016\007" +
    "\067\010\016\011\011\012\007\013\004\017\012\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
       	StringBuffer m = new StringBuffer("Error");
		System.out.println("Mensaje: "+message);
		System.out.println("info: "+info.toString());
		if(info instanceof java_cup.runtime.Symbol) {
			java_cup.runtime.Symbol s=((java_cup.runtime.Symbol)info);
			/* Comprueba si el numero de línea es mayor o igual que cero */
			if(s.left >= 0) {
				m.append(" en linea "+(s.left+1));
				/*Comprueba si el numero de columna es mayor o igual que cero */
				if (s.right >= 0)
					m.append(", y columna "+(s.right+1));
			}
		}
		m.append(" : "+message);
		System.err.println(m);
    }
    public void report_fatal_error(String message, Object info) {
       	report_error(message, info);
		System.exit(1);
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // terminator ::= CRLF 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("terminator",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // terminator ::= SEMICOLON 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("terminator",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // terminator ::= CRLF terminator 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("terminator",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // terminator ::= SEMICOLON terminator 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("terminator",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // number ::= INT 
            {
              ASTNode RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT= new Constante(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("number",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // reference ::= ID 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("reference",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // assignment ::= ID ASIGNACION rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // bucle_if ::= IF condif_list THEN CRLF expression_list ELSE CRLF expression_list END 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bucle_if",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // div ::= number DIV rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("div",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // mul ::= number MUL rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("mul",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // minus ::= number MINUS rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("minus",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // plus ::= number PLUS rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("plus",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // rvalue ::= number 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rvalue",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // rvalue ::= div 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rvalue",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // rvalue ::= mul 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rvalue",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // rvalue ::= minus 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rvalue",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // rvalue ::= plus 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rvalue",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // string ::= LITERAL 
            {
              ASTNode RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Cadena(l);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("string",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // puts ::= PUTS string 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT= new Print(s);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("puts",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // puts ::= PUTS expression 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puts",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expression_bool ::= rvalue COMPARACION rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_bool",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expression_bool ::= BOOLEAN 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_bool",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // condif_list ::= expression_bool 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condif_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // condif_list ::= expression_bool LOGICO condif_list 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condif_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expression ::= assignment 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expression ::= rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expression ::= reference 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expression ::= BOOLEAN 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentence ::= bucle_if 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentence",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentence ::= rvalue 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentence",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentence ::= reference 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentence",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentence ::= assignment 
            {
              ASTNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentence",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentence ::= puts 
            {
              ASTNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode p = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT= new Sentence(p);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentence",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expression_list ::= sentence terminator 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                      RESULT= new SentenceList(s);

                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expression_list ::= sentence terminator expression_list 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode el = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT= new SentenceList(s,el);

                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // prog ::= expression_list 
            {
              Object RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode el = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		Map <String, Object> prog=new HashMap<String, Object>();
                        el.execute(prog);
                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

