
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 27 18:03:02 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 6;
  public static final int ELSE = 4;
  public static final int PLUS = 13;
  public static final int INT = 10;
  public static final int THEN = 5;
  public static final int END = 3;
  public static final int LITERAL = 19;
  public static final int IF = 2;
  public static final int ID = 11;
  public static final int BOOLEAN = 9;
  public static final int COMPARACION = 17;
  public static final int ASIGNACION = 12;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int MINUS = 14;
  public static final int CRLF = 7;
  public static final int error = 1;
  public static final int PUTS = 8;
  public static final int MUL = 15;
  public static final int LOGICO = 18;
}

