
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 25 12:24:45 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 12;
  public static final int INT = 6;
  public static final int BOOLEAN = 16;
  public static final int THEN = 5;
  public static final int PLUS = 11;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int DIV = 14;
  public static final int ELSE = 4;
  public static final int ID = 7;
  public static final int ASIGNACION = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 9;
  public static final int PUTS = 15;
  public static final int MUL = 13;
  public static final int CRLF = 10;
  public static final int END = 3;
}

