
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 25 01:32:31 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 15;
  public static final int ELSE = 9;
  public static final int INT = 11;
  public static final int ELSIF = 8;
  public static final int THEN = 10;
  public static final int WHILE = 4;
  public static final int END = 7;
  public static final int IF = 3;
  public static final int ID = 12;
  public static final int UNLESS = 5;
  public static final int DO = 2;
  public static final int COMPARACION = 14;
  public static final int ASIGNACION = 13;
  public static final int EOF = 0;
  public static final int OPERADOR = 17;
  public static final int CRLF = 16;
  public static final int error = 1;
  public static final int UNTIL = 6;
}

